config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    #pybo/urls.py에서 처리함
]

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

pybo/models.py
from django.db import models

# Create your models here.
#필요한 것들을 class로 작성한다. 
class Question(models.Model):
    subject = models.CharField(max_length = 200) #200자까지 입력 가능하다. 
    content = models.TextField() #글자 수 제한이 없는 데이터
    create_date = models.DateTimeField() #시간 관련 속성

    def __str__(self):
        return self.subject


class Answer(models.Model):
    #질문에 대한 답변이므로 question을 모델 속성으로 가져야 한다. 
    #foreignkey는 다른 모델과의 연결을 의미한다. 
    question = models.ForeignKey(Question, on_delete=models.CASCADE) #답변에 연결된 질문이 삭제되면 답변도 함께 삭제하라
    content = models.TextField()
    create_date = models.DateTimeField()

pybo/forms.py
from django import forms
from pybo.models import Question, Answer
class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content' : 'answer content',
        }

pybo/views.py
from .forms import QuestionForm, AnswerForm
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.core.paginator import Paginator
from .models import Question

# Create your views here.
def index(request):
    return HttpResponse("Hello :D")

def index(request):
    page = request.GET.get('page', '1')
    #question 모델 데이터를 템플릿 파일을 사용하여 화면에 출력할 수 있다. 
    question_list = Question.objects.order_by('-create_date') #생성 날짜의 역순으로 출력
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list' : page_obj}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question' : question}
    return render(request, 'pybo/question_detail.html', context)

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer=form.save(commit=False)
            answer.create_date=timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question':question, 'form' : form}
    return render(request, 'pybo/question_detail.html', context)

def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question=form.save(commit=False)
            question.create_date=timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form' : form}
    return render(request, 'pybo/question_form.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html land="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!--Bootstrap CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}" />
    <!--pybo CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <title>tomato world!</title>
</head>
<body>
<!--basic templates-->
{% include "navbar.html" %}
{%block content%}
{%endblock%}
<!--jQuery JS-->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!--Bootstrap JS-->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">tomatoWorld</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">log-in</a>
            </li>
        </ul>
    </div>
</nav>

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <h2 class="border-bottom py-2">{{question.subject}}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space:pre-line;">
                {{question.content}}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light py-2">
                    {{question.create_date}}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
        {{question.answer_set.count}} answers available
    </h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{answer.content}}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{answer.create_date}}
                </div>
            </div>
        </div>
    </div>
    {%endfor%}

    <form action="{%url 'pybo:answer_create' question.id %}"
        method="post" class="my-3">
        {%csrf_token%}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{field.label}}</strong>
            {{field.errors}}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea name="content" id="content"
                      class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="register" class="btn btn-primary" />
    </form>
</div>


{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">register a question</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <label for="subject">title</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{form.subject.value|default_if_none:''}}" />
        </div>
        <div class="form-group">
            <label for="content">content</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{form.content.value|default_if_none:''}}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">save</button>

    </form>
</div>

{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>number</th>
            <th>title</th>
            <th>date-time</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1}}</td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">
                    {{question.subject}}
                </a>
            </td>
            <td>{{question.create_date}}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">no question</td>
        </tr>
        {% endif %}
        </tbody>

    </table>
    <ul class="pagination justify-content-center">
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link"
               href="?page={{question_list.previous_page_number}}">
                pre
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                pre
            </a>
        </li>
        {% endif %}
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{page_number}}">
                    {{page_number}}
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{page_number}}">
                    {{page_number}}
                </a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link"
               href="?page={{question_list.next_page_number}}">
                post
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                post
            </a>
        </li>
        {% endif %}
        
    </ul>
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">register a question</a>
</div>
{% endblock %}